defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

whitelist: &whitelist
  paths:
    - assets/*
    - bin/*
    - lib/*
    - node_modules/*
    - src/*
    - test/*
    - coverage/*
    - .babelrc
    - .gitignore
    - build/*
    - package.json
    - README.md
version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Test Code
          command: npm run test

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  coveralls:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Submit coverage report to Coveralls.io
          command: npm run coveralls

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build Code
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run: 
          name: Write NPM Token 2 ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run: 
          name: Install dot-json
          command: npm install dot-json

      - run:
          name: Write Version 2 package.json
          command: $(npm bin)/dot-json package.json version ${CIRCLE_TAG:1}

      - run:
          name: Publish 2 NPM
          command: npm run publish2npm

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - coveralls:
          requires:
            - test
      - build:
          requires:
            - test

  release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
      - coveralls:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
          requires:
            - test
      - build:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
#          requires:
#            - test
      - deploy:
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
          requires:
            - build
